export const SAMPLE_MUTATIONS_SET = 'SAMPLE_MUTATIONS_SET';
export const SAMPLE_ACTION_INIT = 'SAMPLE_ACTION_INIT';
export const SAMPLE_ACTIONS_PLUS = 'SAMPLE_ACTIONS_PLUS';
export const SAMPLE_ACTIONS_PLUS_ASYNC = 'SAMPLE_ACTIONS_PLUS_ASYNC';
