export const USER_GETTERS_USER = 'USER_GETTERS_USER';
export const USER_MUTATIONS_SET_USER = 'USER_MUTATIONS_SET_USER';

export const LOADING_GETTERS_LOADING = 'LOADING_GETTERS_LOADING';
export const LOADING_MUTATIONS_SET_LOADING = 'LOADING_MUTATIONS_SET_LOADING';

export const DIRECTION_GETTERS_DIRECTION = 'DIRECTION_GETTERS_DIRECTION';
export const DIRECTION_MUTATIONS_SET_DIRECTION =
  'DIRECTION_MUTATIONS_SET_DIRECTION';
